added remove choosen song from queue feature
Aquerr/FutrzakBot pull request #9
Opened 2022-03-18 18:11 UTC by Shimozuke

2022-03-19 06:01 UTC, Aquerr requested changes

2022-03-19 06:01 UTC, Aquerr commented on src/main/java/io/github/aquerr/futrzakbot/audio/FutrzakAudioPlayer.java
> +import java.util.*;
Fajnie by było jakbyś mógł zachować te wszystkie importy zamiast dawać gwiazdkę

2022-03-19 06:01 UTC, Aquerr commented on src/main/java/io/github/aquerr/futrzakbot/audio/FutrzakAudioPlayer.java
> +
Pusta linijka do wywalenia :stuck_out_tongue_winking_eye:

2022-03-19 06:01 UTC, Aquerr commented on src/main/java/io/github/aquerr/futrzakbot/command/RemoveComand.java
> +        return "Usuń element z kolejki.";
Może "Usuń utwór z kolejki."?

2022-03-19 06:01 UTC, Aquerr commented on src/main/java/io/github/aquerr/futrzakbot/command/RemoveComand.java
> +        return ":poop: Wyrzuć utwór";
Tu serio ma być :hankey: ? :sweat_smile:

2022-03-19 06:01 UTC, Aquerr commented on src/main/java/io/github/aquerr/futrzakbot/audio/FutrzakAudioPlayerManager.java
> +        if (0 > element && element < futrzakAudioPlayer.getQueue().size())
Ten warunek nie zadziała dla ostatniego utworu w kolejce. Jeśli utworów będzie 10 a element=10 to wpadniemy w blok "else".

2022-03-19 06:01 UTC, Aquerr commented on src/main/java/io/github/aquerr/futrzakbot/message/FutrzakMessageEmbedFactory.java
> +        embedBuilder.setTitle(":warning: " + element + " jest poza kolejką :warning:");
A może wstawilibyśmy do title ":warning: Niepoprawna pozycja utworu" a w description "element znajduje się poza kolejką"?

2022-03-21 09:43 UTC, Shimozuke commented on src/main/java/io/github/aquerr/futrzakbot/audio/FutrzakAudioPlayer.java
> +
serio?

2022-03-21 09:44 UTC, Shimozuke commented on src/main/java/io/github/aquerr/futrzakbot/audio/FutrzakAudioPlayer.java
> +import java.util.*;
intellij sam tak zrobił, ja ręcznie nie importuje

2022-03-21 09:59 UTC, Shimozuke commented on src/main/java/io/github/aquerr/futrzakbot/audio/FutrzakAudioPlayerManager.java
> +        if (0 > element && element < futrzakAudioPlayer.getQueue().size())
masz racje, ale tak widzę że ten warunek w ogóle nie będzie działać (0>element)😜

2022-03-21 10:00 UTC, Shimozuke commented on src/main/java/io/github/aquerr/futrzakbot/command/RemoveComand.java
> +        return ":poop: Wyrzuć utwór";
Why not? Skoro ktoś usuwa nawet bez przesłuchania to raczej to jest 💩

2022-03-21 10:06 UTC, Shimozuke commented on src/main/java/io/github/aquerr/futrzakbot/command/RemoveComand.java
> +        return "Usuń element z kolejki.";
ok, yes lord

2022-03-21 10:08 UTC, Shimozuke commented on src/main/java/io/github/aquerr/futrzakbot/message/FutrzakMessageEmbedFactory.java
> +        embedBuilder.setTitle(":warning: " + element + " jest poza kolejką :warning:");
yes lord

2022-03-21 14:38 UTC, Aquerr commented on src/main/java/io/github/aquerr/futrzakbot/audio/FutrzakAudioPlayer.java
> +import java.util.*;
To zmień ustawienia Intellij :stuck_out_tongue_winking_eye:

2022-03-21 14:38 UTC, Aquerr commented on src/main/java/io/github/aquerr/futrzakbot/audio/FutrzakAudioPlayer.java
> +
Poważnie

2022-03-21 14:39 UTC, Aquerr commented on src/main/java/io/github/aquerr/futrzakbot/command/RemoveComand.java
> +        return "Usuń element z kolejki.";
Good, my padawan

2022-03-21 14:42 UTC, Aquerr commented on src/main/java/io/github/aquerr/futrzakbot/command/RemoveComand.java
> +        return ":poop: Wyrzuć utwór";
Myślę że można byłoby użyć :wastebasket:

2022-03-21 15:11 UTC, Aquerr approved these changes

2022-03-22 08:28 UTC, merged